# GitHub Actions: Build & Deploy .NET 8 API to Azure Web App (OIDC)
name: Build & Deploy Core 8 API

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev|uat|prd)"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ github.event_name == 'workflow_dispatch'
                && github.event.inputs.environment != ''
                && fromJson(format('["{0}"]', github.event.inputs.environment))
                || fromJson('["dev"]') }}
    environment: ${{ matrix.env }}

    env:
      PROJECT_FILE: api\src\example-api\example\example.csproj  # <-- update to your actual path
      PUBLISH_DIR: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: |
          dotnet restore "$PROJECT_FILE"
          dotnet publish "$PROJECT_FILE" -c Release -o "$PUBLISH_DIR" /p:UseAppHost=false


      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Get ACR loginServer
        run: echo "LOGIN=${{ vars.ACR_LOGIN_SERVER }}" >> $GITHUB_ENV
        # (set ACR_LOGIN_SERVER as an org/repo variable = module.acr.login_server)
      - name: Build & push
        run: |
          IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/myapi:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      - name: Point Web App to new image
        run: |
          az webapp config container set \
            --resource-group ${{ secrets.RG }} \
            --name my-private-webapp \
            --docker-custom-image-name $IMAGE \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io